vocab/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views


app_name = "vocab"

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name="index"),
    url(r'^training/(?P<pk>[0-9]+)', views.TrainingView.as_view(), name="training")
]

vocabtrainer/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import registration
from registration.backends.simple.views import RegistrationView
from myregistration.views import MyRegistrationView
from . import views


urlpatterns = [
    url(r'^vocab/', include('vocab.urls')),
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls', namespace='accounts')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
]

vocab/models.py
from django.db import models
from django.contrib.auth.models import User


class Learnset(models.Model):
    """
    Objects of this class represent learn-sets including a
    various number of vocabulary or definitions that a
    human can be trained on.
    """
    # name of the learn-set
    learnset_name = models.CharField(max_length=200)

    # related to a certain user
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    # creation date
    creation_date = models.DateTimeField('date created')

    # object's representation
    def __str__(self):
        return self.learnset_name


class Vocabulary(models.Model):
    """
    Objects of this class represent vocab-/definition-pairs
    related to a certain learn-set-object.
    """
    # related to certain learn-set
    learnset = models.ForeignKey(Learnset, on_delete=models.CASCADE)

    # attributes
    word = models.CharField(max_length=200)
    translation = models.CharField(max_length=200)
    forms = models.CharField(max_length=200, default="", blank=True)
    forms_enabled = models.BooleanField(default=False)

    # object's representation
    def __str__(self):
        return self.word

myregistration/views.py
from registration.backends.simple.views import RegistrationView
from django.contrib.auth.models import Permission
from django.contrib.auth import authenticate, get_user_model, login
from registration import signals


User = get_user_model()

class MyRegistrationView(RegistrationView):
    """
    Overrides django-registration RegistrationView class
    """
    def register(self, form):
        new_user = form.save()
        new_user = authenticate(
            username=getattr(new_user, User.USERNAME_FIELD),
            password=form.cleaned_data['password1']
        )
        # access to admin panel
        new_user.is_staff = True

        # permissions
        permission = Permission.objects.get(name="Can add learnset")
        new_user.user_permissions.add(permission)
        permission = Permission.objects.get(name="Can change learnset")
        new_user.user_permissions.add(permission)
        permission = Permission.objects.get(name="Can delete learnset")
        new_user.user_permissions.add(permission)
        permission = Permission.objects.get(name="Can add vocabulary")
        new_user.user_permissions.add(permission)
        permission = Permission.objects.get(name="Can change vocabulary")
        new_user.user_permissions.add(permission)
        permission = Permission.objects.get(name="Can delete vocabulary")
        new_user.user_permissions.add(permission)

        new_user.save()
        
        login(self.request, new_user)
        signals.user_registered.send(sender=self.__class__,
                                     user=new_user,
                                     request=self.request)
        return new_user

    def get_success_url(self, user):
        return '/vocab'

vocab/views.py
from django.shortcuts import render
from django.views import generic

from .models import Learnset


class IndexView(generic.ListView):
    """
    Index-view for vocab-app
    """
    template_name = 'vocab/index.html'

    context_object_name = 'sets'

    def get_queryset(self):
        """
        Getting queryset for index-page of vocab-app
        """
        return Learnset.objects.all().order_by('-creation_date')


class TrainingView(generic.DetailView):
    """
    Shows trainings-session
    """
    template_name = 'vocab/training.html'

    context_object_name = 'learnset'

    def get_queryset(self):
        return Learnset.objects.all()

vocabtrainer/views.py
from django.shortcuts import render


def index(request):

    return render(request, 'vocabtrainer/index.html')

templates/vocabtrainer/index.html
<!DOCTYPE html>
<head>
    <title>Django-Vocab-Trainer</title>
    <meta charset="utf-8">
</head>
<body>
    <header>
        <h1>Django-Vocab-Trainer</h1>
        <span id="top-nav">
            <a href="{% url 'accounts:registration_register' %}">Sign up</a>
            <a href="{% url 'accounts:auth_login' %}">Sign in</a>
        </span>
    </header>
    <section>
        <h1>Short description</h1>
        <p>
            This is an application which lets you create learn-sets including
            vocabulary or definitions you want to learn.<br>
            To use it you only have to sign up an account (you will be logged
            in automatically) or login to an existing one.
        </p>
        <p>
            The project itself is available on <a href="https://github.com/DahlitzFlorian/django-vocab-trainer">Github</a>
            so you even can fork it, create issues or contribute to this project.
        </p>
</body>
</html>

vocab/templates/vocab/index.html
<!DOCTYPE html>
<head>
    <title>Django-Vocab-Trainer</title>
    <meta charset="utf-8">
</head>
<body>
    <header>
        <h1>Django-Vocab-Trainer</h1>
        <span id="top-nav">
            <a href="{% url 'accounts:auth_logout' %}">Sign out</a>
        </span>
    </header>
    <section>
        <h1>Your Learn-sets</h1>
        <ul>
            {% for set in sets %}
            <li><a href="{% url 'vocab:training' set.id %}">{{ set.learnset_name }}</a></li>
            {% endfor %}
        </ul>
    </section>
</body>
</html>

vocab/templates/vocab/training.html
{% load static %}
<!DOCTYPE html>
<head>
    <title>Django-Vocab-Trainer</title>
    <meta charset="utf-8">

    <!-- Other Stylesheets -->
    <link rel="stylesheet" href="https://meyerweb.com/eric/tools/css/reset/reset.css" type="text/css">
    <!-- Own Stylesheets -->
    <link rel="stylesheet" href="{% static 'vocab/style.css' %}" type="text/css">

    <!-- Own Scripts -->
    <script src="{% static 'vocab/training.js' %}" type="text/js"></script>
</head>
<body>
    <header>
        <h1>Django-Vocab-Trainer</h1>
        <span id="top-nav">
            <a href="{% url 'accounts:auth_logout' %}">Sign out</a>
        </span>
    </header>
    <section>
        <table>
            <tbody>
                <tr>
                    <td id="f19" ></td>
                    <td id="f20" ></td>
                    <td id="f21" ></td>
                    <td id="f22" ></td>
                    <td id="f23" ></td>
                    <td id="f24" ></td>
                    <td id="f25" class="control"></td>
                </tr>
                <tr>
                    <td id="f14" ></td>
                    <td id="f15" ></td>
                    <td id="f16" ></td>
                    <td id="f17" ></td>
                    <td id="f18" class="control"></td>
                </tr>
                <tr>
                    <td id="f9" ></td>
                    <td id="f10" ></td>
                    <td id="f11" ></td>
                    <td id="f12" ></td>
                    <td id="f13" class="control"></td>
                </tr>
                <tr>
                    <td id="f4" ></td>
                    <td id="f5" ></td>
                    <td id="f6" ></td>
                    <td id="f7" ></td>
                    <td id="f8" class="control"></td>
                </tr>
                <tr>
                    <td id="f1" ></td>
                    <td id="f2" ></td>
                    <td id="f3" class="control"></td>
                </tr>
            </tbody>
        </table>
    </section>
</body>
</html>